In [1]:
# Different types of Merge layers:
# (1) Concatenate
# (2) Average
# (3) Maximum
# (4) Minimum
# (5) Add
# (6) Subtract
# (7) Multiply
# (8) Dot

In [2]:
# Importing Important libraries
import tensorflow as tf
import numpy as np

In [3]:
# Generating raw data
x = np.arange(20).reshape(2,2,5)
print('X : ', x)
y = np.arange(20, 30).reshape(2,1,5)
print('y : ', y)

X :  [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
y :  [[[20 21 22 23 24]]

 [[25 26 27 28 29]]]


In [4]:
# Concatenating
tf.keras.layers.Concatenate(axis = 1)([x, y])

<tf.Tensor: shape=(2, 3, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29]]])>

In [5]:
# Making 2 layers and concatenating them
x1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
x2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
concatted = tf.keras.layers.Concatenate()([x1, x2])
concatted.shape

TensorShape([5, 16])

In [6]:
# Average Layer

In [7]:
# Getting Raw Data
x1 = np.ones((2, 2))
x2 = np.zeros((2, 2))
y = tf.keras.layers.Average()([x1, x2])
y.numpy().tolist()


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



[[0.5, 0.5], [0.5, 0.5]]

In [8]:
# Average Layer
input1 = tf.keras.layers.Input(shape = (16,))
x1 = tf.keras.layers.Dense(8, activation = 'relu')(input1)
input2 = tf.keras.layers.Input(shape = (32,))
x2 = tf.keras.layers.Dense(8, activation = 'relu')(input2)
avg = tf.keras.layers.Average()([x1, x2])
out = tf.keras.layers.Dense(4)(avg)
model = tf.keras.models.Model(inputs = [input1, input2], outputs = out)

In [9]:
# Model Summary
model.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 16)]         0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 32)]         0                                            
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 8)            136         input_1[0][0]                    
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 8)            264         input_2[0][0]                    
_______________________________________________________________________________________

In [10]:
# Maximum Layer

In [11]:
# Example 1
tf.keras.layers.Maximum()([np.arange(5).reshape(5, 1),
                          np.arange(5, 10).reshape(5, 1)])

<tf.Tensor: shape=(5, 1), dtype=int64, numpy=
array([[5],
       [6],
       [7],
       [8],
       [9]])>

In [12]:
# Example 2
x1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
x2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
maxed = tf.keras.layers.Maximum()([x1, x2])
maxed.shape

TensorShape([5, 8])

In [13]:
# Minimum Layer

In [14]:
# Example 1
tf.keras.layers.Minimum()([np.arange(5).reshape(5, 1),
                          np.arange(5, 10).reshape(5, 1)])

<tf.Tensor: shape=(5, 1), dtype=int64, numpy=
array([[0],
       [1],
       [2],
       [3],
       [4]])>

In [15]:
# Example 2
x1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
x2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
mined = tf.keras.layers.Minimum()([x1, x2])
mined.shape

TensorShape([5, 8])

In [16]:
# Add Layers

In [17]:
# Example 1
input_shape = (2, 3, 4)
x1 = tf.random.normal(input_shape)
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Add()([x1, x2])
print(y.shape)

(2, 3, 4)


In [18]:
# Example 2 
input1 = tf.keras.layers.Input(shape = (16,))
x1 = tf.keras.layers.Dense(8, activation = 'relu')(input1)
input2 = tf.keras.layers.Input(shape = (32,))
x2 = tf.keras.layers.Dense(8, activation = 'relu')(input2)
added = tf.keras.layers.Add()([x1, x2])
out = tf.keras.layers.Dense(4)(added)
model = tf.keras.models.Model(inputs = [input1, input2], outputs = out)

In [19]:
# Model Summary
print(model.summary())

Model: "functional_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 16)]         0                                            
__________________________________________________________________________________________________
input_4 (InputLayer)            [(None, 32)]         0                                            
__________________________________________________________________________________________________
dense_9 (Dense)                 (None, 8)            136         input_3[0][0]                    
__________________________________________________________________________________________________
dense_10 (Dense)                (None, 8)            264         input_4[0][0]                    
_______________________________________________________________________________________

In [20]:
# Substract Layers

In [21]:
# Example 1
input_shape = (2, 3, 4)
x1 = tf.random.normal(input_shape)
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Subtract()([x1, x2])
print(y.shape)

(2, 3, 4)


In [22]:
# Example 2 
input1 = tf.keras.layers.Input(shape = (16,))
x1 = tf.keras.layers.Dense(8, activation = 'relu')(input1)
input2 = tf.keras.layers.Input(shape = (32,))
x2 = tf.keras.layers.Dense(8, activation = 'relu')(input2)
added = tf.keras.layers.Subtract()([x1, x2])
out = tf.keras.layers.Dense(4)(added)
model = tf.keras.models.Model(inputs = [input1, input2], outputs = out)

In [23]:
# Model Summary
print(model.summary())

Model: "functional_5"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_5 (InputLayer)            [(None, 16)]         0                                            
__________________________________________________________________________________________________
input_6 (InputLayer)            [(None, 32)]         0                                            
__________________________________________________________________________________________________
dense_12 (Dense)                (None, 8)            136         input_5[0][0]                    
__________________________________________________________________________________________________
dense_13 (Dense)                (None, 8)            264         input_6[0][0]                    
_______________________________________________________________________________________

In [24]:
# Multiply Layer

In [25]:
# Example 1
tf.keras.layers.Multiply()([np.arange(5).reshape(5, 1),
                          np.arange(5, 10).reshape(5, 1)])

<tf.Tensor: shape=(5, 1), dtype=int64, numpy=
array([[ 0],
       [ 6],
       [14],
       [24],
       [36]])>

In [26]:
# 0,1,2,3,4
# 5,6,7,8,9

In [27]:
# Example 2 
input1 = tf.keras.layers.Input(shape = (16,))
x1 = tf.keras.layers.Dense(8, activation = 'relu')(input1)
input2 = tf.keras.layers.Input(shape = (32,))
x2 = tf.keras.layers.Dense(8, activation = 'relu')(input2)
added = tf.keras.layers.Multiply()([x1, x2])
out = tf.keras.layers.Dense(4)(added)
model = tf.keras.models.Model(inputs = [input1, input2], outputs = out)

In [28]:
# Model Summary
print(model.summary())

Model: "functional_7"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_7 (InputLayer)            [(None, 16)]         0                                            
__________________________________________________________________________________________________
input_8 (InputLayer)            [(None, 32)]         0                                            
__________________________________________________________________________________________________
dense_15 (Dense)                (None, 8)            136         input_7[0][0]                    
__________________________________________________________________________________________________
dense_16 (Dense)                (None, 8)            264         input_8[0][0]                    
_______________________________________________________________________________________

In [29]:
# Dot Layer

In [30]:
# Raw Data
x = np.arange(10).reshape(1, 5, 2)
print('X : ', x)
y = np.arange(10, 20).reshape(1, 2, 5)
print('y : ', y)

X :  [[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
y :  [[[10 11 12 13 14]
  [15 16 17 18 19]]]


In [31]:
# Dot Product
tf.keras.layers.Dot(axes = (1, 2))([x, y])

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[260, 360],
        [320, 445]]])>

In [32]:
# Example
x1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
x2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
dotted = tf.keras.layers.Dot(axes = 1)([x1, x2])
print(dotted.shape)

(5, 1)
